apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: demo-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "0" # Tạo cùng lúc với deployment
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
